# Generated by Django 3.2.6 on 2021-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='adr',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Infosys', max_length=100),
        ),
    ]
