# Generated by Django 3.2.6 on 2021-08-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210807_1808'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='emp',
        ),
    ]
