# Generated by Django 3.2.6 on 2021-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='id',
        ),
        migrations.AlterField(
            model_name='license',
            name='license_no',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
