# Generated by Django 3.2.6 on 2021-08-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeline',
            field=models.DateTimeField(null=True),
        ),
    ]
