# Generated by Django 3.2.6 on 2021-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_task_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeline',
            field=models.DateTimeField(),
        ),
    ]
