# Generated by Django 3.2.6 on 2021-08-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(db_column='emp_projects', to='app1.Employee'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
